### ISSUE TITLE
Code about evaluating other training methods in Table 2, 6, 7, 8, and 9 in the paper:

### ISSUE THREAD

**Issue by kevinbro96** [cassidylaidlaw/perceptual-advex#1]
In table  2, 6, 7, 8, and 9, you compare PAT with other AT methods. Did you train other AT methods based on your code, if yes, can you share the code?

**Comment by cassidylaidlaw** [comment]
Yes, we did train all the AT models using this code. You can, for instance, train a model on CIFAR-10 against L-infinity attacks using this command:

    python adv_train.py --batch_size 50 --arch resnet50 --dataset cifar --attack "LinfAttack(model, bound=8, num_iterations=10)"

All of the models we evaluated, both PAT and AT trained, can be downloaded [here](https://perceptual-advex.s3.us-east-2.amazonaws.com/perceptual-advex-checkpoints.zip). In that zip file is a README that describes exactly which checkpoints were evaluated for each table in the paper.

**Comment by kevinbro96** [comment]
Thank you very much, very clear and nice code.

**Comment by cassidylaidlaw** [comment]
You're welcome! Feel free to open another issue if you have any other questions about the code/paper.
