### ISSUE TITLE
How to run AT-Trades using your code?

### ISSUE THREAD

**Issue by kevinbro96** [cassidylaidlaw/perceptual-advex#11]
How to run AT-Trades using your code?

**Comment by cassidylaidlaw** [comment]
Our code can't run TRADES training, but you can evaluate the CIFAR-10 TRADES model that's available [on the TRADES repo](https://github.com/yaodongyu/TRADES) by running

    python evaluate_trained_model.py --dataset cifar --checkpoint /path/to/model_cifar_wrn.pt --arch trades-wrn --batch_size 50 --output evaluation.csv \
    "NoAttack()" \
    "AutoLinfAttack(model, 'cifar', bound=8/255)" \
    "AutoL2Attack(model, 'cifar', bound=1)" \
    "StAdvAttack(model, num_iterations=100)" \
    "ReColorAdvAttack(model, num_iterations=100)" \
    "PerceptualPGDAttack(model, num_iterations=40, bound=0.5, lpips_model='alexnet_cifar', projection='newtons')" \
    "LagrangePerceptualAttack(model, num_iterations=40, bound=0.5, lpips_model='alexnet_cifar', projection='newtons')"
    
The linked repo also has training code for TRADES if you're interested in running it.
