### ISSUE TITLE
Curl other files

### ISSUE THREAD

**Issue by rydeveraumn** [cassidylaidlaw/perceptual-advex#14]
Hi @cassidylaidlaw!

Thank you for this great work. Is there a list of files that are available through curl? I want to download only specific pre-trained models like in this command:

`!curl -o data/checkpoints/cifar_pgd_l2_1.pt https://perceptual-advex.s3.us-east-2.amazonaws.com/cifar_pgd_l2_1_cpu.pt`

I am interested in `cifar_pat_self_0.5.pt`

I tried:

`!curl -o my_directory https://perceptual-advex.s3.us-east-2.amazonaws.com/cifar_pat_self_0_5_cpu.pt`

Thank you in advance.

**Comment by cassidylaidlaw** [comment]
Hi @rydeveraumn, thanks for your interest in the paper! I believe the only checkpoints you can download individually are the ones in the getting started notebook. Is it an issue for you to download all the checkpoints and just take the one you need? If it is, I might be able to put that one up.

**Comment by rydeveraumn** [comment]
Hey @cassidylaidlaw I don't think it will be :) I was just wondering if I was missing anything. I am able to `wget` the zipped models successfully. Thank you for such a quick response!

**Comment by cassidylaidlaw** [comment]
Great, glad to hear!
