### ISSUE TITLE
The adversarial samples are normalized twice.

### ISSUE THREAD

**Issue by kevinbro96** [cassidylaidlaw/perceptual-advex#2]
The PGD code you use will normalize the adversarial samples.
https://github.com/ddkang/advex-uar/blob/bddc970e5a4ea8c5fee2ea5c349ddd29d83bf88d/advex_uar/attacks/attacks.py#L92

However, your model also normalizes the input adversarial samples.
https://github.com/cassidylaidlaw/perceptual-advex/blob/70af18f174a269ed17368116b41e59e10cad0195/perceptual_advex/models.py#L159

Thus, the adversarial samples are normalized twice, does this matters?

**Comment by cassidylaidlaw** [comment]
I believe the normalizer for the UAR attacks (including PGD) is removed here in the wrapper we use:
https://github.com/cassidylaidlaw/perceptual-advex/blob/70af18f174a269ed17368116b41e59e10cad0195/perceptual_advex/attacks.py#L203
Let me know if you still think there is a problem.

**Comment by kevinbro96** [comment]
Thank you ! There is no problem.
