### ISSUE TITLE
How does the classifier model store in the attack module update with the training procedure?

### ISSUE THREAD

**Issue by kevinbro96** [cassidylaidlaw/perceptual-advex#3]
You define the attack module before the training precedure and the classifier model is stored in the attack module with:
https://github.com/cassidylaidlaw/perceptual-advex/blob/70af18f174a269ed17368116b41e59e10cad0195/perceptual_advex/perceptual_attacks.py#L91
I wonder how the classifier model stored in the attack update with the training procedure?

**Comment by cassidylaidlaw** [comment]
In python, all class instances are stored by reference, so the classifier model referenced by `attack.model` is the same object as the classifier model trained in the `adv_train` script. As the model is trained, the same model is still referenced by `attack.model`, so the attack has access to the updated model. The answers here might help clarify: https://stackoverflow.com/questions/986006/how-do-i-pass-a-variable-by-reference.

**Comment by kevinbro96** [comment]
Thank you.
