### ISSUE TITLE
checkpoint of alexnet

### ISSUE THREAD

**Issue by tao-bai** [cassidylaidlaw/perceptual-advex#7]
Hi, may I have the checkpoints of alexnet like alexnet_imagenet100.pt and alexnet_cifar.pt? 
I didn't find them here https://perceptual-advex.s3.us-east-2.amazonaws.com/perceptual-advex-checkpoints.zip

**Comment by cassidylaidlaw** [comment]
Hi, the CIFAR-10 AlexNet checkpoint can be downloaded from https://perceptual-advex.s3.us-east-2.amazonaws.com/alexnet_cifar.pt. The ImageNet-100 AlexNet checkpoint is the same as the pretrained `torchvision` one; you can load it by calling `torchvision.models.alexnet(pretrained=True)`. In the code, there is also a useful function for loading both these checkpoints (it will automatically download them):

```python
from perceptual_advex.perceptual_attacks import get_lpips_model
alexnet_imagenet100 = get_lpips_model('alexnet')
alexnet_cifar10 = get_lpips_model('alexnet_cifar')
```

Hope this helps! Let me know if you have any more questions.

**Comment by tao-bai** [comment]
I see. Thank you!
