### ISSUE TITLE
Bounds for StAdv and ReColor attacks

### ISSUE THREAD

**Issue by pratyushmaini** [cassidylaidlaw/perceptual-advex#9]
Hi, Could you help me in figuring out the correct bounds for the StAdv and Recolor attacks for both CIFAR10 and Imagenet100? It wasn't clear to me from my initial reading of the paper or the code.

Thanks in advance!

**Comment by cassidylaidlaw** [comment]
Hi @pratyushmaini, thanks for your interest in the paper/code. The default bounds for both attacks in the code (0.05 for StAdv and 0.06 for ReColorAdv) match the bounds used throughout the paper. Table 4 in the appendix shows all the bounds used for ImageNet-100 (we used the "medium" bounds) if you're curious about what we used for other attacks.

**Comment by cassidylaidlaw** [comment]
Yup, that's right.

**Comment by pratyushmaini** [comment]
Thanks. Closing the issue
